### ISSUE TITLE
Implement some GL tracing/debugging macros and use them consequently

### ISSUE THREAD

**Issue by wattyka** [simple2d/simple2d#10]
Currently, there is only basic GL error handling implemented. As the first GLES implementation has show on the RPI, many GL function failures can stay unnoticed and rendering might just fail without any clues why. Use of simple macros after a gL function call ,like i.e. a GLECLEAR()/GLECHECK() internally calling glGetError()/assert and/or tracing something, would make the situation much easier without much work or drawbacks on performance.

**Comment by blacktm** [comment]
Error checking has gotten much more robust and consistent, so closing this issue for now.
