### ISSUE TITLE
C++ build command is incorrect

### ISSUE THREAD

**Issue by tomalakgeretkal** [simple2d/simple2d#118]
https://github.com/simple2d/simple2d/blob/master/bin/simple2d.sh#L209

When the input is C++, the build command should use `g++` (to trigger linking in of the standard library) and `-std=c++11` (to avoid an error).

This has led to [problems in the field](https://stackoverflow.com/q/59536040/560648).

**Comment by blacktm** [comment]
Just merged #119, thanks again.
