### ISSUE TITLE
Improve platform detection

### ISSUE THREAD

**Issue by blacktm** [simple2d/simple2d#14]
The hardware/OS platform detection could be more robust. This detection happens in a few places: in the [Makefile](https://github.com/simple2d/simple2d/blob/master/Makefile#L3), the [`simple2d.sh` script](https://github.com/simple2d/simple2d/blob/master/simple2d.sh#L635), and also the [`simple2d.h` include](https://github.com/simple2d/simple2d/blob/master/include/simple2d.h#L3) (if `__arm__`, then assume GLES).

See @ukscone's ideas for RPI in #13.

**Comment by ukscone** [comment]
As the Pi is "special" within ARM devices i'd probably uname -m and if resolves to armv6l or armv7l check if it's a Pi using the grep method where whether it's a Pi or not makes a difference

**Comment by blacktm** [comment]
This has gotten much more robust, so I'll close for now.
