### ISSUE TITLE
Add Homebrew include dir /usr/local/include

### ISSUE THREAD

**Issue by grrussel** [simple2d/simple2d#30]
Family-iMac:S2D grrussel$ cc HelloTriangle.c `simple2d --libs` -o triangle
HelloTriangle.c:1:10: fatal error: 'simple2d.h' file not found
#include <simple2d.h>
         ^
1 error generated.
Family-iMac:S2D grrussel$ simple2d --libs
-lsimple2d -I/usr/local/include/SDL2 -D_THREAD_SAFE
-L/usr/local/lib -lSDL2 -Wl,-framework,OpenGL -lSDL2_image -lSDL2_mixer -lSDL2_ttf
Family-iMac:S2D grrussel$ ls /usr/local/include/
FLAC		jerror.h	png.h		tiff.h		vorbis
FLAC++		jmorecfg.h	pngconf.h	tiffconf.h	webp
SDL2		jpeglib.h	pnglibconf.h	tiffio.h
freetype2	libpng16	simple2d.h	tiffio.hxx
jconfig.h	ogg		smpeg2		tiffvers.h

**Comment by blacktm** [comment]
This might be an issue with your Homebrew installation. I'd take a look at their [troubleshooting guide](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting) and try reinstalling Simple 2D.

**Comment by blacktm** [comment]
Going to close this for now, but happy to reopen if we find it's not a Homebrew issue.

**Comment by grrussel** [comment]
xcode-select install

For some reason, the Xcode Command Line tools needed to be installed in order to get /usr/local/include on the include path

**Comment by blacktm** [comment]
Ah yes, Apple requires their tools before unlocking `/usr/local` directories. Homebrew should have installed those tools with their own installation, strange. Running `brew doctor` is a good first step for any issues that might pop up in the future.
