### ISSUE TITLE
Missing dependency in installer script

### ISSUE THREAD

**Issue by andrewhavens** [simple2d/simple2d#31]
I just got a [PocketCHIP](https://nextthing.co/) from a Kickstarter that I supported a couple years ago. I'm playing around with it and would like to install Simple2D on it. I ran the installer. It detected the device as a Raspberry Pi (similar hardware, running Debian Linux). It successfully installed SDL, but failed on installing Simple2D. Here's the backtrace:

```
==> Checking for SDL2... yes
==> Checking for SDL2_image... yes
==> Checking for SDL2_mixer... yes
==> Checking for SDL2_ttf... yes

Info: SDL was installed successfully

==> Downloading Simple 2D...

==> curl -L https://github.com/simple2d/simple2d/archive/v0.2.1.zip -o /tmp/simple2d/v0.2.1.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122    0   122    0     0    234      0 --:--:-- --:--:-- --:--:--   235
100 33605    0 33605    0     0  30297      0 --:--:--  0:00:01 --:--:--  282k

==> Unpacking...

==> unzip -q /tmp/simple2d/v0.2.1 -d /tmp/simple2d
==> cd /tmp/simple2d/simple2d-0.2.1

==> Compiling...

==> make
/dev/fd/63: line 111: make: command not found

==> Installing...

==> sudo make install
sudo: make: command not found

==> Cleaning up...

==> rm -rf /tmp/simple2d

==> Checking for simple2d... no

Error: Simple 2D did not install correctly
```

Looks like it could not find `make`. I was a little surprised. I think I need to install `build-essential`. Maybe it's a dependency that should be added to the installer script?

**Comment by andrewhavens** [comment]
Once I installed `build-essential`, the installer worked. Here's a picture of the triangle example running on my PocketCHIP!

![img_3212](https://cloud.githubusercontent.com/assets/446392/16218492/443404ae-3733-11e6-8823-87d7a8c5f1d3.JPG)

**Comment by blacktm** [comment]
Hey Andrew – It's been a while! Hope things are good.

I just checked out the CHIP project. Very cool to see other mini-computing platforms sprout up in addition to the Pi. And really dig the PocketCHIP concept. Bummer I missed the Kickstarter :)

I'm also pretty surprised `make` is missing, and I'm guessing the entire C build system found in [`build-essential`](https://packages.debian.org/jessie/build-essential) as well. Especially weird seeing as it's marketed to be a hackable platform. Oh well, it's easy enough to check for the `build-essential` package. I'll open a new issue to add that.

Your issue description also suggests another change which can be made to the install script and Makefile. Now that there are other platforms than just the Pi, it's worth taking a page from the world of web development and not "read the UA string" to infer the environment, but rather do proper feature detection. I've got `rpi` hardcoded in there quite a bit, but what really matters is whether it's an OpenGL ES platform or not. Main thing I've been looking for is `arm` in the `uname -m` string, and then assume GLES if present. There's probably issues with that approach also, but that's the best I've got for now. I'll start a new issue to at least abstract away the `rpi` stuff to be a general `arm` platform instead.

Other than that, I'm pretty stoked it worked (mostly) out-of-the-box without any crazy configuration nonsense. And thanks for sharing the pic – awesome to see that little multi-colored triangle appear perfectly on a new piece of hardware (well, maybe a bit too big for a 480x272 screen, but close enough).

**Comment by andrewhavens** [comment]
Yeah! I've been having fun with this. It's been a while since I've done any C/Ruby 2D programming. So it's also been a while since I've seen your latest updates to S2D and R2D. I like what I see. Nice work! I've been digging into the code a lot lately, but so far almost everything is working as expected. I'm running into an issue with detecting my USB game controller on the PocketCHIP. I'm running against a clone of the ruby2d repo so that I could enable `S2D_Diagnostics`. =]

If you know how to check for GLES, let me know and I can see if the CHIP is considered GLES or not.

**Comment by andrewhavens** [comment]
Just ran a script with diagnostics enabled and saw the following:
```
Error: (Mix_Init) Mixer not build with MP3 support
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
Info: OpenGL Context
GL_VENDOR: Mesa Project
GL_RENDERER: Software Rasterizer
GL_VERSION: 2.1 Mesa 10.3.2
GL_MAJOR_VERSION: 5
GL_MINOR_VERSION: 2
GL_SHADING_LANGUAGE_VERSION: 1.20
```
not sure if that means anything to you. Unfortunately, I did not see any logging about the controller. I'll open a different issue for that.

**Comment by andrewhavens** [comment]
Oh by the way, I'm working on running some SDL tests. I saw this when I ran `./configure` which you might find interesting:

```
./configure 
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for an ANSI C-conforming const... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SDL... yes
checking how to run the C preprocessor... gcc -E
checking for X... libraries , headers 
checking for OpenGL support... yes
checking for OpenGL ES support... no
checking for OpenGL ES2 support... yes
checking for TTF_Init in -lSDL2_ttf... yes
configure: creating ./config.status
```

**Comment by blacktm** [comment]
Hey @andrewhavens, I've pushed a lot of updates this past week to better handle generic ARM platforms. The missing `build-essential` is fixed, and the [install pathway for ARM/OpenGL ES](https://github.com/simple2d/simple2d/blob/master/simple2d.sh#L271) is much improved. Since most of the SDL2 Debian packages are built with X11 and OpenGL (desktop stuff), the install script now downloads and builds SDL2 (and image, mixer, ttf) from source with friendlier config flags.

All tests pass on the Raspberry Pi and geometry looks great, but for some reason textures don't get rendered at all. I'm still trying to figure out what's going on there.

If you're so inclined, it would be awesome to see if the testcard works on the PocketCHIP. Easiest way to test this would be:
1. Cloning the repo using `git clone --recursive https://github.com/simple2d/simple2d.git`
2. `cd`ing into the directory and installing SDL with the script: `sudo bash simple2d.sh install --sdl`
3. And finally running tests: `sudo test.sh auto testcard`

I'd be interested to see what happens!

**Comment by blacktm** [comment]
Since the dependency issue is fixed, I'll close this. We can open a new one if running the testcard presents issues.
