### ISSUE TITLE
Not detecting controller on CHIP

### ISSUE THREAD

**Issue by andrewhavens** [simple2d/simple2d#35]
I have a game controller ([this one](http://amzn.to/29mr0nF)) that I am using. It works when I use it on my Mac and in other programs running on my PocketCHIP. Now that I have diagnostics enabled, I see this output when I run the script on my Mac:

```
Info: OpenGL Context
GL_VENDOR: Intel Inc.
GL_RENDERER: Intel(R) Iris(TM) Graphics 6100
GL_VERSION: 4.1 INTEL-10.14.66
GL_MAJOR_VERSION: 4
GL_MINOR_VERSION: 1
GL_SHADING_LANGUAGE_VERSION: 4.10
Info: Joysticks detected: 1
Warning: Joystick 0 is not supported by the game controller interface
Info: Opened Joystick 0
Name: USB,2-axis 8-button gamepad  
Axes: 2
Buttons: 8
Balls: 0
```

When I run the same script on my PocketCHIP, it does not output any of the controller diagnostic logging. As far as I know, I am using the same version of Simple2D on both platforms.

**Comment by blacktm** [comment]
I have the same controller! Love it.

If no controllers are found, there won't be any diagnostic output ([see the implementation](https://github.com/simple2d/simple2d/blob/master/src/simple2d.c#L635)). If [`SDL_NumJoysticks()`](https://wiki.libsdl.org/SDL_NumJoysticks) is returning `0`, then none are being detected. If it's returning a negative number, then some error is occurring.

Here's the simplest program you can write to test all this:

```c
#include <simple2d.h>

int main() {
  S2D_CreateWindow(NULL, 100, 100, NULL, NULL, 0);
  
  printf("%i\n", SDL_NumJoysticks());
  printf("Error: %s\n", SDL_GetError());
  
  return 0;
}
```

I'll be interested to hear what you find out.

**Comment by blacktm** [comment]
This _may_ have been fixed with the updates described in https://github.com/simple2d/simple2d/issues/31#issuecomment-241124346. Would be interested hear if this works now!

**Comment by blacktm** [comment]
@andrewhavens Any updates?

**Comment by blacktm** [comment]
Is this the same issue?
http://stackoverflow.com/questions/38087203/how-to-test-handle-sdl2-game-controller-inputs

Looks like you figured it out, yes?

**Comment by andrewhavens** [comment]
Hey Tom, sorry, haven't had much time lately to keep up. I did find the problem and the solution. It actually was not a problem with Simple2D, but with the way SDL was reporting controller input. And the CHIP was ignoring this type of input. Once I found and updated that config it started working. I found/posted the answer in the CHIP forums. I'll try to find the link. Haven't tried the latest changes to Simple2D but looking forward to it.

**Comment by blacktm** [comment]
No problem, thanks for the update! As evident by this (12 day) delayed response, I wish I also had more time for side projects :)  Glad you figured it out. I found the link in the [CHIP forums](https://bbs.nextthing.co/t/usb-controller-for-pico-8-on-pocketc-h-i-p/5077/13) – not sure if there's a convenient, automated way to check for this. Might just have to make a FAQ wiki page or something.
