### ISSUE TITLE
Define homebrew mechanism to try latest code

### ISSUE THREAD

**Issue by grrussel** [simple2d/simple2d#36]
Family-iMac:assembly grrussel$ brew install simple2d --HEAD
Error: No head is defined for simple2d/tap/simple2d

The webpage readme links to the very latest testcard, but that is now using the Sprite API added after 0.2.1 was released.

**Comment by blacktm** [comment]
Great idea! Just added `head` to the tap (https://github.com/simple2d/homebrew-tap/commit/853c429bbdea9c1a43ba04556f600caca4c0b567).

As far as the documentation getting out of sync, yea, that's my bad. @andrewhavens made [a suggestion](https://github.com/simple2d/simple2d/issues/32#issuecomment-229256700) on how to address it, so I'll give that a try.
