### ISSUE TITLE
Support for multiple controllers or joysticks

### ISSUE THREAD

**Issue by grrussel** [simple2d/simple2d#39]
Patch indicating how multiple controller support can be added - essentially, just passing the SDL numeric ID into "on_controller" to let the application to separate inputs per controller

https://gist.github.com/grrussel/6bf44e5b058af61865ecc4a70a2c0753

**Comment by blacktm** [comment]
Yea, makes sense to me!

**Comment by grrussel** [comment]
See pull request #40
