### ISSUE TITLE
S2D_DrawCircle

### ISSUE THREAD

**Issue by grrussel** [simple2d/simple2d#42]
It would be nice if Simple2D had native support for drawing circles, and not just Triangles.

Love2D has an implementation of this (under the zlib/libpng license); see https://bitbucket.org/rude/love/src/0a33429ed4b64d491c13ec6fcf9d167fe202d048/src/modules/graphics/opengl/Graphics.cpp?at=default&fileviewer=file-view-default

I have ported that to my own programming language - which wraps Simple2D in its standard library - to obtain the following, allowing me to draw coloured circles with a specified number of segments - from repeated calls to DrawTriangle.

Of note; it is slow to call DrawTriangle repeatedly - it may be preferable to have a DrawTriangles to avoid overheads from calling into the OpenGL driver repeatedly

    PROCEDURE DrawEllipse*(xi,yi,ai,bi, points :INTEGER;
                                              c1,c2,c3 : S2D_Colour);
    VAR M_PI , TWO_PI:FLOAT; 
    VAR angleShift, phi : FLOAT;
    VAR coords : ARRAY OF FLOAT;
    VAR i : INTEGER;
    VAR x,y,a,b:FLOAT;
    BEGIN
      M_PI   := 3.14159265358979323846;
      TWO_PI := 2.0 * M_PI;
      x := RT.ToFloat(xi); y := RT.ToFloat(yi);
      a := RT.ToFloat(ai); b := RT.ToFloat(bi);
  
     IF points <= 0 THEN points := 1 END;

     angleShift := TWO_PI / RT.ToFloat(points);
     phi := 0.0;

     NEW(coords,2*(points+1));
  
     WHILE i < points DO
        coords[2*i+0] := x + a * RT.Cos(phi);
        coords[2*i+1] := y + b * RT.Sin(phi);
        phi := phi + angleShift; i := i + 1;
     END;

     coords[2*points+0] := coords[0];
     coords[2*points+1] := coords[1];

     i := 0;
     WHILE i < points DO    
        DrawTriangle(x,y,
                 c1.r, c1.g, c1.b, c1.a,
                 coords[2*i+0],  coords[2*i+1],
                 c2.r, c2.g, c2.b, c2.a,
                 coords[2*i+2],  coords[2*i+3],
                 c3.r, c3.g, c3.b, c3.a);
        i := i + 1;
    END;

    END DrawEllipse;

    PROCEDURE DrawCircle*(x,y,radius, points :INTEGER;
                      c1,c2,c3 : S2D_Colour);
    BEGIN
       DrawEllipse( x, y, radius, radius, points, c1, c2, c3 );
    END DrawCircle;

**Comment by blacktm** [comment]
Absolutely, it would be great to support more primitives, and circles are a great place to start. Probably the most efficient approach is just to implement them in OpenGL directly, for example using a [triangle fan](https://gist.github.com/strife25/803118) (this is legacy GL, so would also need to figure out how to do that in modern GL using vertex shaders, which shouldn't be too difficult).

I'll do some research, try a few things and see what works. Also, pretty impressive you're building your own language!

**Comment by grrussel** [comment]
I have modified my S2D install locally to have a "DrawTriangles" call for the OpenGL3 backend; this does expose the data format (arrays of sequences of 8 floats to represent a vertex) to the calling application 

[patch](https://gist.github.com/grrussel/12d59d987c4907a4f3ce42d75a97d37f)

**Comment by blacktm** [comment]
Implemented in 7511e1551d0b028c64316d7d394a81fe68cdd515.
