### ISSUE TITLE
Feature Request - Controller Input Events similar to keyboard

### ISSUE THREAD

**Issue by grrussel** [simple2d/simple2d#43]
It would be nice to have continuous input events while an Axis or Button is held in, similar to the case of what is done on holding down a key

**Comment by blacktm** [comment]
Yes, very important to know if a button is being held. Not sure if you saw, but I [recently added](https://github.com/simple2d/simple2d/commit/753e79fade6304787f8bc2d50b7828cea92b3a82) a "pressed" callback parameter, so it's easy to tell what state the button is in. For axes, they don't really have a pressed state, but rather `on_controller` is called whenever the value of an axis changes.

If you haven't yet, give the [`controller.c`](https://github.com/simple2d/simple2d/blob/master/tests/controller.c) test a try (it's not yet in a release, so you'll have to pull the latest changes from master and `make rebuild && make controller`. I'd be interested to hear if this meets your needs.
