### ISSUE TITLE
Hide cursor on Raspberry Pi?

### ISSUE THREAD

**Issue by Tuckers** [simple2d/simple2d#45]
Is there a way to hide the mouse cursor on Raspberry Pi? 
I'm running my app from console, but it appears in the upper left of the screen one openGL context is enabled. I'm using a Raspberry Pi 3

**Comment by blacktm** [comment]
Yes, absolutely. This library is built on SDL, which provides a convenient function called [`SDL_ShowCursor`](https://wiki.libsdl.org/SDL_ShowCursor). For consistency, I'd like to add a `S2D_HideCursor(<true or false>)` or something, but for now you can directly call `SDL_ShowCursor(SDL_DISABLE)` anywhere after `S2D_CreateWindow` and that should do the trick.

**Comment by Tuckers** [comment]
Awesome, thanks for the quick response.

**Comment by blacktm** [comment]
Just added a `S2D_ShowCursor` function in 6b3070d4af6b36e50fe132a8d481ee76e7fc34f8, and is queued up for the next release.
