### ISSUE TITLE
Flag for window orientation

### ISSUE THREAD

**Issue by Tuckers** [simple2d/simple2d#46]
Not sure about the feasibility of this, but I'm trying to build a portrait (vertical orientation) game, and the raspberry pi has terrible performance when using "display_rotate=1" [see description](https://github.com/raspberrypi/firmware/issues/403). 

I'm wondering if there's an additional window flag that could be added to implement the rotation in the openGL/VG layer to avoid poor performance, and keep it easy to still do coding/testing on a horizontal monitor?

**Comment by blacktm** [comment]
Yes, totally possible, just have to mess around with the [projection matrix](https://github.com/simple2d/simple2d/blob/master/src/gl.c#L11). Now to brush up on my [matrix algebra](https://open.gl/transformations)  😬

**Comment by Tuckers** [comment]
If you get a solution implemented I'll send you a case of beer. The alternative is to hardcode the orientation into my game. 😞

**Comment by blacktm** [comment]
Cheers to that 🍻! And hardcoding things sideways sounds awful, don't do that 🙂

Alright, quick hack: in `gl.c` / `S2D_GL_SetViewport` before the `S2D_GL*_ApplyProjection` functions get called ([line 202 here](https://github.com/simple2d/simple2d/blob/ce4eabc93ff68a10ab13a75a756f9a7e7f3ced07/src/gl.c#L202)), add the following to rotate the projection matrix clockwise 90°:

```c
  GLfloat a = 1.0f / (window->orig_width  / 2.0f);
  GLfloat b = 1.0f / (window->orig_height / 2.0f);
  
  orthoMatrix[0] = orthoMatrix[0] - a;
  orthoMatrix[1] = -a;
  orthoMatrix[4] = -b;
  orthoMatrix[5] = orthoMatrix[5] + b;
  orthoMatrix[12] = 1.0f;
```

It doesn't account for a window with a non-equal width and height, and doesn't translate the mouse position. It'll take some effort to make a fancy API for rotating the viewport/window, but for now you could clone the repo, add this change, and run `make rebuild` to uninstall / compile / reinstall. Hope that helps a bit!

**Comment by blacktm** [comment]
This could be quite complex to implement at the graphics API layer, but maybe an easier route is through the OS display settings, [like this](https://askubuntu.com/questions/1043644/how-to-rotate-screen-in-ubuntu-using-terminal) for example.
