### ISSUE TITLE
Can't find GLES2/gl2platform.h

### ISSUE THREAD

**Issue by BasPaap** [simple2d/simple2d#47]
I installed simple2d on Raspbian using the bash script provided in the readme file, and it seems to have worked okay except **SDL_opengles2.h** is expecting a **GLES2** directory containing **gl2platform.h**, **gl2.h** and **gl2ext.h**, which I am unable to find anywhere.  **sudo find / -name gl2platform.h** came up empty. 

Anyone know what went wrong?

**Comment by blacktm** [comment]
Hmm, the Raspberry Pi firmware includes those files in the [`/opt/vc/include/GLES2`](https://github.com/raspberrypi/firmware/tree/master/opt/vc/include/GLES2) directory. Not sure why you'd be missing them.

**Comment by BasPaap** [comment]
Oh hey, there they are. Great! I'm not sure why find couldn't find them at first. Thanks for the info!

**Comment by blacktm** [comment]
Sure thing. And just to note, when running `simple2d --libs` on the Pi, `-I/opt/vc/include/ -L/opt/vc/lib` gets added to the output so the compiler will find them.
