### ISSUE TITLE
Can't build on Raspberry Pi 2

### ISSUE THREAD

**Issue by BasPaap** [simple2d/simple2d#48]
I've installed Simple2D on a RPi 1 running Raspbian via the remote script mentioned in Readme.md. I tried building the triangle demo but it fails to compile. I've checked and simple2d.h is in /usr/local/include and libsimple2d.a is in usr/local/lib. When I run `simple2d build main.cpp`, I get the following response:

> /tmp/cclqqZ8u.o: In function `render()':
> main.cpp:(.text+0x5c): undefined reference to `S2D_DrawTriangle(float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float)'
> /tmp/cclqqZ8u.o: In function `main':
> main.cpp:(.text+0xb0): undefined reference to `S2D_CreateWindow(char const*, int, int, void (*)(), void (*)(), int)'
> main.cpp:(.text+0xc0): undefined reference to `S2D_Show(S2D_Window*)'
> main.cpp:(.text+0xc8): undefined reference to `S2D_FreeWindow(S2D_Window*)'
> collect2: error: ld returned 1 exit status

So it looks like somehow something went wrong during the linking, but I can't figure out what it could be.

**Comment by blacktm** [comment]
So here's an admission: I never actually tested the library with C++ source files, only C. I just confirmed the error is the same on macOS when switching the extension of `triangle.c` to `.cpp`. If not too much trouble, you could use C exclusively for now. We should probably create a branch to add C++ support.

**Comment by BasPaap** [comment]
Ah, that explains it then. I wonder how much work it would be to add C++ support, could be an interesting feature to add.

**Comment by blacktm** [comment]
Well, C++ is mostly a superset of C, so they play well together. There's a lot of good guidance out there on [using C in C++](https://isocpp.org/wiki/faq/mixing-c-and-cpp).

Actually, I just tried compiling the renamed `triangle.cpp` and wrapping the Simple 2D header file like so, and it worked fine:

```c
extern "C"
{
  #include <simple2d.h>
}
```

We'd probably want to add some fancy `#ifdef __cplusplus` internally to make this seamless. Thanks for bringing up this line of inquiry — will be a nice thing to add.

**Comment by blacktm** [comment]
Going to close this issue and track C++ support in #49.
