### ISSUE TITLE
Feature Request - Resize sprite

### ISSUE THREAD

**Issue by argusroot** [simple2d/simple2d#52]
Firstly I liked Simple2D a lot !

I tried, without success, to resize the sprite width and height with no effect but some transparent borders.

Is there some way to do this already ?
Thank you again for this amazing library :+1:

**Comment by blacktm** [comment]
Hello, glad you like the project! Just like [images](https://github.com/simple2d/simple2d/tree/v0.5.1#images), you can set the width and height of sprites, for example:

```c
spr->width  = 256;
spr->height = 512;
```

Guess I forgot to document it. Also, while just testing it right now, I'm noticing a glitch where for a frame the sprite snaps back to the original size before being reset to the new size when calling `S2D_ClipSprite` then `S2D_DrawSprite`. Will have to investigate that.

**Comment by blacktm** [comment]
Alright, I think I've got the right behavior worked out here. With #55, we can now set the width and height of the sprite using, for example...

```c
spr->width  = 100;
spr->height = 100;
```

...then whenever `S2D_ClipSprite` is called, the clipping rectangle is applied, and the ratio between the original image size and the modified sprite size is maintained. This means we can set the sprite size, clip it, and the sprite width and height will automatically be set to the proper proportions. Kind of confusing — hope that makes sense!

**Comment by argusroot** [comment]
Amazing !
I will give it a try today. This new feature will be very useful for game development and other interfaces that need animation + scaling.

Thanks again (:

**Comment by blacktm** [comment]
Agreed, will be useful for my games as well. Thanks for the suggestion!
I'll go ahead and merge #55 and close this issue, but happy to revisit if there's some behavior that we want to change.
