### ISSUE TITLE
Support for SDL2 Touch Events

### ISSUE THREAD

**Issue by grrussel** [simple2d/simple2d#59]
Patch of initial support at

https://gist.github.com/grrussel/a9571543408ec1581177e2aed38bb126 

Known limitations: I do not handle windows whose size is not the same as the touch display size, so x,y positions in touch events are incorrect in that case

I have set the window size in testcard.c to the size of my touchscreen

**Comment by blacktm** [comment]
Very cool! Maybe you saw the iOS progress in the [Gitter chat](https://gitter.im/ruby2d/ruby2d) — if not, great timing 🙂
Are you comfortable opening a PR?

**Comment by grrussel** [comment]
Hopefully the PR is working OK

I just got a https://shop.pimoroni.com/collections/raspberry-pi/products/hyperpixel Touch display for the PI

**Comment by blacktm** [comment]
Nice, I've been meaning to buy a little touch display for my RPI. Looks like a good one — do you like it?
Just gave the PR a try on my iPhone, and it works great! Should be a simple thing to merge.

**Comment by grrussel** [comment]
The screen seems to have some build quality or robustness issues - dead pixels on the first, dead display on the replacement ( just touch events working then ); A shame, as apart from the dead pixels the 1st is fine for use...

**Comment by blacktm** [comment]
Moving over to implementation in #60.
