### ISSUE TITLE
installscript fails

### ISSUE THREAD

**Issue by UweKrause** [simple2d/simple2d#63]
Hey everybody,
trying to install with the install script as stated in the README fails.
It installs the dependencies, but fails while building simple2d.
It's Debian 8.
What can I do?

```
Welcome to Simple 2D!
---------------------
[...]
==> Checking for SDL2... yes
==> Checking for SDL2_image... yes
==> Checking for SDL2_mixer... yes
==> Checking for SDL2_ttf... yes

==> Downloading Simple 2D
[...]
==> Unpacking
[...]
==> make

==> Building

mkdir -p build
[...]
cc -std=c11 -fPIC  src/window.c -c -o build/window.o
src/window.c: In function ‘S2D_Show’:
src/window.c:176:61: error: ‘SDL_MouseWheelEvent’ has no member named ‘direction’
               .type = S2D_MOUSE_SCROLL, .direction = e.wheel.direction,
                                                             ^
Makefile:60: recipe for target 'window' failed
make: *** [window] Error 1

==> sudo make install

==> Installing Simple 2D
[...]
==> Checking for simple2d... no

Error: Simple 2D did not install correctly

```

**Comment by blacktm** [comment]
Hmm, I wonder if the Debian SDL package is out of date. Could you run `sdl2-config --version` and see what it says? Looks like `direction` was added to [`SDL_MouseWheelEvent` in version 2.0.4](https://wiki.libsdl.org/SDL_MouseWheelEvent). Perhaps we should add a SDL version check to the install script.

**Comment by UweKrause** [comment]
Its 2.0.2
( https://packages.debian.org/jessie/libsdl2-dev )
There are no newer backports available for jessie (debian 8 oldstable), which otherwise could have been a simple way to get a newer version. 

In the current stable release debian 9 (stretch) it would be 2.0.5
( https://packages.debian.org/stretch/libsdl2-dev )

BUT:
Even when I build sdl 2.0.5 myself, it fails.
(I just followed the sdl2 make guide, I have no idea if there have been any problems or missing dependencies. It "made" something and sdl2-config --version said 2.0.5 afterwards)
https://wiki.libsdl.org/Installation

For the moment I will look around for other ways to create a simple 2d game, but if I could help you somehow, please let me know.

**Comment by blacktm** [comment]
We'll take up the minimum SDL version check in #74.

**Comment by marcofognog** [comment]
I am having the same issued described by UweKrause
