### ISSUE TITLE
Required iOS SDK / XCode versions?

### ISSUE THREAD

**Issue by grrussel** [simple2d/simple2d#64]
It looks like my SDK is too old

Family-iMac:ios grrussel$ simple2d build --ios deps/xcode/ios/
xcpretty not found: Run `gem install xcpretty` for nicer xcodebuild output.

Build settings from command line:
    SDKROOT = iphonesimulator9.2

=== BUILD TARGET MyApp OF PROJECT MyApp WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
iOS deployment target '10.3' for architecture 'x86_64' and variant 'normal' is greater than the maximum value '9.2.99' for the Simulator - iOS 9.2 SDK.

**Comment by blacktm** [comment]
Yea, I built everything against the latest SDK, 10.3 for iOS. I wonder if you could open the Xcode project and change the deployment target SDK version. Or just upgrade your SDK. Not sure if I should make it clear what SDK versions to use.

**Comment by grrussel** [comment]
In the end, the iOS version of my phone requires a new Xcode requires a new OSX etc....

There comes a point when its simpler to say OSX 10.12 + SDK 10.3 :-)

**Comment by blacktm** [comment]
Ah yes, that's characteristically Apple 😄
