### ISSUE TITLE
Missing iOS tvOS Frameworks via Homebrew

### ISSUE THREAD

**Issue by grrussel** [simple2d/simple2d#65]
Following the instructions seems to not result in the required frameworks

Family-iMac:Documents grrussel$ brew tap simple2d/tap
==> Tapping simple2d/tap
Cloning into '/usr/local/Homebrew/Library/Taps/simple2d/homebrew-tap'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
Tapped 1 formula (28 files, 21.2KB)
Family-iMac:Documents grrussel$ brew install simple2d --HEAD
==> Installing simple2d from simple2d/tap
==> Cloning https://github.com/simple2d/simple2d.git
Updating /Users/grrussel/Library/Caches/Homebrew/simple2d--git
==> Checking out branch master
==> make
==> make install PREFIX=/usr/local/Cellar/simple2d/HEAD-c407789
🍺  /usr/local/Cellar/simple2d/HEAD-c407789: 7 files, 107.1KB, built in 8 seconds
Family-iMac:Documents grrussel$ ls -a /usr/local/Frameworks/
.	..
Family-iMac:Documents grrussel$ simple2d build

Use the build command to compile or build Simple 2D apps.

For compiling C/C++ source files, use:
  build <c_or_cpp_file>

To build an Xcode project, use:
  build <sdk_option> <optional_path_to_xcode_project>

For <sdk_option> above, use one of the following:
  --ios            iOS simulator SDK
  --ios-device     iOS device SDK (requires signing)
  --tvos           tvOS simulator SDK
  --tvos-device    tvOS device SDK (requires signing)

**Comment by blacktm** [comment]
Yea, sorry, haven't updated the formula yet, which requires a new release to be cut, which takes a bit of time but hope to have done soon. In the meantime, you could:
1. `git clone --recursive https://github.com/simple2d/simple2d.git`, cd `simple2d/`
2. `make release` — to make the frameworks
3. `make install-frameworks` — to install them
4. (optionally) Run `make ios` and `make tvos` to build and launch the test triangle for iOS and tvOS, respectively.

**Comment by grrussel** [comment]
Yup, I built from source in the end; one issue I stumbled on is that the Xcode projects were not looking for the Frameworks in the /usr/local/Frameworks directory

(I have seen the triangle in an iPhone sim ;-) )

**Comment by blacktm** [comment]
I just pushed some updates in 98338600fe69ad62559773281c0e5757e6777e5a so that the example Xcode projects look for the Simple2D.framework in `/usr/local/Frameworks/Simple2D`, instead of the source root as before. Hope that makes things a bit easier and more consistent with building desktop apps. Still have to publish a new release and update the Homebrew formula, but wanted to give an update in the meantime. Thanks!

**Comment by blacktm** [comment]
Just released [0.7.0](https://github.com/simple2d/simple2d/releases/tag/v0.7.0) and updated the Homebrew tap. Frameworks will now get installed to `/usr/local/Frameworks`
