### ISSUE TITLE
Calling S2D_DrawText in render() displays corrupted text

### ISSUE THREAD

**Issue by valtonia** [simple2d/simple2d#67]
Hi,

This may be expected behaviour and I'm just using this wrong, so please forgive me if I'm just being a noob. :)

So, I create a new text object in my constructor using _S2D_CreateText_ for use as a timer.  In my _update()_ method I _snprintf_ a counter into a string and use _S2D_SetText_ on my object to change the text (once per second), and in my _render()_ method I call _S2D_DrawText_ on the object.

This causes the text to become corrupted.

If I move the _S2D_SetText_ into the _render()_ method then all is fine.  Is this how it's supposed work?  or should I be able to set the text elsewhere and then keep rendering it over and over?

Many thanks.

**Comment by blacktm** [comment]
Hi @valtonia, yes, that's how I intended for it to be used. In reality, I doesn't (or shouldn't) matter where you call `S2D_SetText`. Given that the `render()` function might be skipped if a cycle of the window loop is long (reducing the framerate), setting the text in `update()` might be preferred.

I did a little test moving around `S2D_SetText` to see if I could reproduce what you're describing, but wasn't able to. Do you have a code snippet you could share? Also helpful would be what OS you're on and terminal output of the snipped with `S2D_Diagnostics(true);` in there before you create the window. Thanks!

**Comment by valtonia** [comment]
Hi, thanks for trying.  I tried to put my code back as it was with `S2D_SetText ` in the `update()` method, but I also couldn't reproduce the problem.  Perhaps it was something else causing it?, but at the time I could reproduce it by moving the call between `update()` and `render()`.

I'll keep an eye on it (I'm still in the quite early stages of game dev) and let you know if it happens again.  Just for information: I'm using Win10 64-bit and the _vera.ttf_ font - pretty much as per the example in the documentation.

Many thanks.

**Comment by blacktm** [comment]
Hmm, could have been any number of things. I do remember fixing a bug related to the order of `S2D_SetText/DrawText` — maybe there's still an edge case lingering. Oh well, we'll keep a lookout for funky text textures. Thanks.
