### ISSUE TITLE
S2D_DrawText crash

### ISSUE THREAD

**Issue by grrussel** [simple2d/simple2d#68]
There is a check in S2D_SetText for null and empty string

      // `msg` cannot be an empty string or NULL for TTF_SizeText
      if (msg == NULL || strlen(msg) == 0) msg = " ";

but it is possible to call S2D_DrawText before S2D_SetText, leading to a crash as TTF_RenderText_Blended fails to create a surface, returns NULL, and the  S2D_GL_CreateTexture call indexes into the null pointer; below, is a version of S2D_DrawText with a check added to avoid the crash and report the error via S2D_Error

    /*
     * Draw text
     */
    void S2D_DrawText(S2D_Text *txt) {
      if (!txt) return;

       if (txt->texture_id == 0) {
          SDL_Color color = { 255, 255, 255 };
          txt->surface = TTF_RenderText_Blended(txt->font, txt->msg, color);
          if (!txt->surface) {
             S2D_Error("TTF_RenderText_Blended", TTF_GetError());
             return ;
          }
        S2D_GL_CreateTexture(&txt->texture_id, GL_RGBA,
                             txt->width, txt->height,
                             txt->surface->pixels, GL_NEAREST);
        SDL_FreeSurface(txt->surface);
      }

      S2D_GL_DrawText(txt);
    }

Info: Current display mode is 1920x1080px @ 60hz
Info: OpenGL Context
      GL_VENDOR: Intel Inc.
      GL_RENDERER: Intel Iris Pro OpenGL Engine
      GL_VERSION: 4.1 INTEL-10.25.17
      GL_SHADING_LANGUAGE_VERSION: 4.10
Error: (TTF_RenderText_Blended) Text has zero width

**Comment by blacktm** [comment]
Might be related to #67.
