### ISSUE TITLE
fatal error on <simple2d.h> on Mac.

### ISSUE THREAD

**Issue by Help-sekser** [simple2d/simple2d#69]
Trying to build a program will cause Building...
build/app.c:1777:10: fatal error: 'simple2d.h' file not found
#include <simple2d.h> 

Which is rather logic due to the fact that  #include <simple2d.h>  is ment for windows. The problem is this will cause the building of .app to fail can anyone help?

**Comment by blacktm** [comment]
Sorry for the delay. If the file is in `/usr/local/include/simple2d.h`, it should be found by the `#include`.

**Comment by blacktm** [comment]
Going to close, but if we get more info, happy to continue investigating.
