### ISSUE TITLE
Calculate FPS using a moving average

### ISSUE THREAD

**Issue by blacktm** [simple2d/simple2d#71]
Right now we're just doing a dumb calculation using [total number of frames rendered](https://github.com/simple2d/simple2d/blob/master/src/window.c#L122), and instead want a [moving average](https://en.wikipedia.org/wiki/Moving_average). Some resources/ideas for implementing:
- https://stackoverflow.com/questions/4687430/c-calculating-moving-fps

**Comment by Dolphindalt** [comment]
Please review my pull request about this issue.

**Comment by blacktm** [comment]
Completed in #84 🎉
