### ISSUE TITLE
Error in command line utility for windows

### ISSUE THREAD

**Issue by glitchroy** [simple2d/simple2d#72]
I'm on Windows 10 x64. After installing Ruby 2.3 and the corresponding devkit, I used the MinGW installation of Simple2D v0.8.0 (the Ruby2D installation guide, basically). Running the following produces an error

```
> bash simple2d
/usr/local/bin/simple2d: simple2d: line 230: syntax error in conditional expression: unexpected token `('
/usr/local/bin/simple2d: simple2d: line 230: syntax error near `^(-'
/usr/local/bin/simple2d: simple2d: line 230: `  if ! [[ $1 =~ ^(--ios|--ios-device|--tvos|--tvos-device)$ ]]; then'
```

Commenting out the code block in `<devkit_location>\local\bin\simple2d` like this
```
229 # If bad SDK flag, print build usage
230 # if ! [[ $1 =~ ^(--ios|--ios-device|--tvos|--tvos-device)$ ]]; then
231 #   print_usage_build; exit 1
232 # fi
```
seems to get rid of the error and launches into the normal simple2d help dialogue.

**Comment by blacktm** [comment]
Hi @glitchroy, thanks for the report. I haven't been able to reproduce this issue specifically, but have been doing a lot of Windows / MinGW troubleshooting lately in conjunction of improving the Ruby 2D experience. We're going to start recommending people use a [MSYS2 / MinGW](https://github.com/simple2d/simple2d/issues/62#issuecomment-355790879) environment, which is now standard for [the latest RubyInstaller](https://rubyinstaller.org/2017/05/25/rubyinstaller-2.4.1-1-released.html) (Ruby 2.4 and beyond). I just pushed new [Ruby 2D on Windows](http://www.ruby2d.com/learn/windows/) instructions, so I hope that helps! Do let us know if you encounter more issues.
