### ISSUE TITLE
Error following instruction for installing simple2d

### ISSUE THREAD

**Issue by marcofognog** [simple2d/simple2d#75]
Installing simple2d from the instructions on README results in error: 

running `./simple2d.sh install:
`
results:

```
 src/window.c:181:61: error: ‘SDL_MouseWheelEvent’ has no member named ‘direction’
                .type = S2D_MOUSE_SCROLL, .direction = e.wheel.direction,

```
PS: Ubuntu, ruby 2.3.1

**Comment by marcofognog** [comment]
Hum, just found it is a known issue https://github.com/simple2d/simple2d/issues/74

I'd suggest we fix this or mention in the README.

**Comment by marcofognog** [comment]
well, after updated sdl2 to
´´´
$sdl2-config --version
2.0.8
´´´
still getting a bunch of errors:
https://gist.github.com/marcofognog/33b1658cb54c969e36bf5720bd778a98

does anyone have any idea?

**Comment by blacktm** [comment]
PR #76 will now check/enforce a minimum SDL version. I have no idea what could be causing those thousands of "previous declaration", "redeclaration", and "conflicting types" errors. Maybe it was the way SDL was built? Here's what we do to [install SDL from source](https://github.com/simple2d/simple2d/blob/ffc0ab724fb14b4eac43faa32f9311bc8d26596b/bin/simple2d.sh#L333). If you want to try running this, uninstall SDL2 and change [this line](https://github.com/simple2d/simple2d/blob/ffc0ab724fb14b4eac43faa32f9311bc8d26596b/bin/simple2d.sh#L432) to `install_sdl_source` and reinstall with `bash install.sh install`. I just tested all this on a fresh, updated install of Ubuntu 17.10.

**Comment by marcofognog** [comment]
Thanks, I'll give it a try and report back

**Comment by marcofognog** [comment]
Fresh SDL installation on ubuntu did trickl

**Comment by blacktm** [comment]
Cool, glad to hear it.
