### ISSUE TITLE
2D Image behind other image

### ISSUE THREAD

**Issue by 072608** [simple2d/simple2d#78]
I'm not 100% sure, if this is an issue, but I can't seem to figure out why my Ace is being drawn behind the 2 instead of it infront, or any other textures, I assume this has to do with Z Axis and the Ace being Z -1 then the 2.  All I do is set the Ace Coord = to Mouse X/Y and 2 has Static Coords. So is there a way to S2D Image Z Axis for say 2.5D issues?
![q5ukqf6](https://user-images.githubusercontent.com/9493634/35896532-ae3a5952-0b8a-11e8-9782-831540661a1b.png)

**Comment by blacktm** [comment]
You may have figured it out, but the order of the objects is really just based on when they were drawn (latest on top). Good luck!
