### ISSUE TITLE
Support for Rotating Images, Text and Sprites

### ISSUE THREAD

**Issue by thomasb892** [simple2d/simple2d#79]
simple2d library could be more widely used if it had support for rotation. It would be easy to add rotation support because both SDL and OpenGL ES/Open GL supports rotation. I would prefer the hardware accelerated OpenGL ES rotation (I'm using simple2d on a Raspberry pi).

**Comment by thomasb892** [comment]
Also, it would be very helpful if you could give me some code that can perform a rotation given degrees/radians. Your code is very simple to understand. I get that you are using a struct with surface as the pointer to SDl Surface. And texture id for drawing the texture in OpenGL(es). However, I don't know OpenGL ES(I only know OpenGL) so I would be very happy if you could throw some code to me that I may include in my program so that I don't need to wait and update simple2d when that feature is added. Thanks in Advance

**Comment by blacktm** [comment]
Agreed, would be a great feature to add. We've talked about it [over at Ruby 2D](https://github.com/ruby2d/ruby2d/issues/30), which uses this lib. To implement, I'd probably add a `rotate` property [to the structs](https://github.com/simple2d/simple2d/blob/v0.9.0/include/simple2d.h#L254), figure out the math ([something like this](https://stackoverflow.com/questions/28124548/rotate-quad-made-in-geometry-shader)), and do these point translations [before drawing here](https://github.com/simple2d/simple2d/blob/v0.9.0/src/gl3.c#L197) for each GL renderer. Now, just have to find the free time to do all the work 😉. In the meantime, I suppose you could write your own `S2D_*_DrawTexture` functions with the rotation math.

**Comment by blacktm** [comment]
Added in #88 🌀
