### ISSUE TITLE
Static lib needs table of contents

### ISSUE THREAD

**Issue by msbit** [simple2d/simple2d#81]
Unsure whether this is strictly a `simple2d` or `homebrew-tap` issue, but after installing `simple2d` via `brew`, the static lib is does not have a table of contents:
```
$ file /usr/local/Cellar/simple2d/0.9.0/lib/libsimple2d.a 
/usr/local/Cellar/simple2d/0.9.0/lib/libsimple2d.a: current ar archive
```
causing the following error:
```
$ ld -arch x86_64 -bundle -macosx_version_min 10.7.0 -L/usr/local/Cellar/simple2d/0.9.0/lib -lsimple2d -o test.bundle
ld: archive has no table of contents for architecture x86_64
$ echo $?
1
```
and ultimately https://github.com/ruby2d/ruby2d/issues/109

As part of the build, it should run `ranlib`, like so:
```
$ ranlib /usr/local/Cellar/simple2d/0.9.0/lib/libsimple2d.a 
ranlib: file: /usr/local/Cellar/simple2d/0.9.0/lib/libsimple2d.a(gles.o) has no symbols
```
after which, the lib has a table of contents:
```
$ file /usr/local/Cellar/simple2d/0.9.0/lib/libsimple2d.a 
/usr/local/Cellar/simple2d/0.9.0/lib/libsimple2d.a: current ar archive random library
```
and `ld` doesn't complain:
```
$ ld -arch x86_64 -bundle -macosx_version_min 10.7.0 -L/usr/local/Cellar/simple2d/0.9.0/lib -lsimple2d -o test.bundle
$ echo $?
0
```

**Comment by blacktm** [comment]
Haven't been able to reproduce this lately. Might be due to the older macOS and dev tools installed (we've been testing on all latest releases).
