### ISSUE TITLE
Issue testing - Can't find entry point inflateValidate in DLL libpng16-16.dll

### ISSUE THREAD

**Issue by kurinoku** [simple2d/simple2d#89]
This seems like a newb error, and it's probably because of my doing... But I don't know where else to put ask...
I'm running Win 10 64-bits with a MSYS2 enviroment, I've installed MINGW64 with make too, I've removed every other instance of C++/C compiler bin folder and colliding dependencies folder from my PATH, and I still get this error from auto, testcard & controller, although controller doesn't crash...
triangle and audio seem to be working properly, I've tried in two computers with the same operating system (Win 10 x64) and in both I get the same results, that's what leads me to believe that I've been doing something wrong...

**Comment by kurinoku** [comment]
Now it works! I still have an issue though, I had to add /mingw64/bin and /mingw64/lib to PATH to make it work (although I suspect the latter did the trick), is this normal behavior? I had to also remove /usr/local/bin from PATH, am I supposed to deliver the programs with the dll included in the same folder?

**Comment by blacktm** [comment]
Wow, that's a really convoluted error message. Googling around, looks like `inflateValidate` is a function defined in zlib, and libpng can't find it. Glad to hear you got around it. Are you using the `mingw64.exe` shell? That should (I hope) include typical `$PATH` entries. I install [MSYS2 via Ruby](http://www.ruby2d.com/learn/windows/), and here's my `$PATH`:

```
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/Ruby24-x64/bin
```

As for delivering the DLLs with your program, yes, I think so. These are dynamic libraries needed at run time. Perhaps there's a way to merge them into a single executable, but I'm not sure.

**Comment by kurinoku** [comment]
Thank you for responding, as for my issue I talked an acquaintance about it and he said that what I did was the way to fix it... I'm going to close this issue now...
