### ISSUE TITLE
Support for overriding the vertex / fragment shader programs

### ISSUE THREAD

**Issue by cubic1271** [simple2d/simple2d#99]
Hi,

It'd be nice to be able to override the default vertex and fragment shaders (for textures and for normal shapes, since there seem to be two different programs used for those respective cases).

The approach to this I'm working through at the moment involves adding a pair of functions to gl3.c that allow me to update shaderProgram and texShaderProgram, and borrowing much of the compilation / boilerplate from S2D_GL3_Init so that I can rebuild them and use my updated copies.  

There's probably a better / cleaner way to do this than what I'm doing, though.

**Comment by blacktm** [comment]
Yes, would be great to expose those pieces via the public API. How do you imagine it would work? We could simply allow people to set their own vertex and fragment shaders globally (I'm not really an OpenGL expert, and so I don't actually know if we could use the same fragment shader for both textured and non-textured objects). We could also let people change the shader programs as objects are being rendered, for example:

```c
S2D_Shader vs = S2D_CreateShader(vertex_source);
S2D_Shader fs = S2D_CreateShader(fragment_source);
S2D_ShaderProgram sp = S2D_CreateShaderProgram(vs, fs);

// When rendering, can select a program prior to drawing
S2D_UseShaderProgram(sp);
S2D_DrawSomething(thing);
S2D_UseShaderProgram(another_shader_program);
S2D_DrawSomething(thing2);
```

Another possibility could be to assign shader programs to individual drawable objects. I might need to understand some use cases more. Let me know your thoughts!

**Comment by cubic1271** [comment]
For what it's worth, I think I like the idea of keeping the shader programs on the objects themselves and letting the DrawXYZ calls apply the program stored as part of the object.  If no shaders have been assigned to the object, then the default programs would be used.

One consideration might be that any custom shader programs would need to include the projection / texture code that exists in the shaders Simple2D uses by default.  That would be something that should probably be documented.

Also - my personal use-case involved a 72-hour game jam with a limitation that only three colors could be used.  I used a random dithering shader to enforce that constraint and achieve an effect I liked.   If it'd help, I could give a link to what I wrote ... but the code is not very clean (partially because of the short amount of time I had to make something work).  I also used a hack to make the shader programs work with Simple2D: I think what you describe would be a much better approach.

As one last note - this library was easy to use and seemed to work as advertised, so ... thanks for writing it!

**Comment by cubic1271** [comment]
Well, I'll take the holiday delay and raise you a year ... I totally missed this reply, and only found it again when I was checking to see if there was a new version of this library.  

Sorry about that.

Game:
https://cubic1271.itch.io/twilightinfinite

Source:
https://bitbucket.org/cubic1271/twilight.infinite/src/master/

Let me see if I can make a change that I think makes sense and that I like better than the hack I made for this.  If so, I'll get a pull request set up and we can talk about if / how it's suited to merge.

**Comment by cubic1271** [comment]
(going to close in the meantime, and will re-open once I have something more complete to talk about)
